config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:"homes#top"
  resources :books do
    resource :favorites ,only:[:create,:destroy]
    resource :comments ,only:[:create,:destroy]
  end
  resources :users ,only:[:show,:edit,:update]
  get "/search",to: "searchs#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many:favorites ,dependent: :destroy
  belongs_to:user
  has_many:comments ,dependent: :destroy
  validates:title,presence:true
  validates:body,presence:true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to:user
  belongs_to:book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many:books ,dependent: :destroy
  has_many:favorites ,dependent: :destroy
  has_many:comments ,dependent: :destroy
  attachment:profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    books_path
  end

  before_action:authenticate_user!,except:[:top]

  before_action:configure_permitted_parameters,if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book=Book.new
    @books=Book.all
    @user=User.find(current_user.id)

    @user_books=@user.books
    @favorites_count=0
    @user_books.each do |book|
      @favorites_count+=book.favorites.count
    end
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:create]="投稿完了しました"
      redirect_to books_path
    else
      @books=Book.all
      render :index
    end
  end

  def show
    @select_book=Book.find(params[:id])
    @comment=Comment.new
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    book=Book.find(params[:book_id])
    comment=current_user.comments.new(comment_params)
    comment.book_id=book.id
    comment.save
    redirect_back(fallback_location:root_path)
  end

  def destroy
    comment=Comment.find_by(book_id:params[:book_id])
    comment.destroy
    redirect_back(fallback_location:root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book=Book.find(params[:book_id])
    favorite=current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location:root_path)
  end

  def destroy
    book=Book.find(params[:book_id])
    favorite=current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location:root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model,@content,@method)
  end

  private
  def search_for(model,content,method)
    if model=="user"
      if method=="perfect"
        User.where(name: content)
      else
        User.where("name LIKE ?","%"+content+"%")
      end
    elsif model=="book"
      if method=="perfect"
        Book.where(title: content)
      else
        Book.where("book LIKE ?","%"+content+"%")
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user=User.find(params[:id])
    @book=Book.new
    @books=@user.books

    @favorites_count=0
    @books.each do |book|
      @favorites_count+=book.favorites.count
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user==current_user
      render:edit
    else
      redirect_to books_path
    end
  end

  def update
    @user=User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private
  def user_params
    params.require(:user).permit(:name,:profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h3>投稿一覧</h3>
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>title</th>
      <th>body</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr>
      <td><a href="/users/<%=book.user.id %>"><%= attachment_image_tag book.user,:profile_image,fallback:"no_image.jpg",size:"60x66" %></a></td>
      <td><a href="/books/<%= book.id %>"><%= book.title %></a></td>
      <td><%= book.body %></td>
      <% if book.user.id==current_user.id %>
        <td></td>
        <td><%= link_to "削除",book_path(book.id) ,method: :delete ,"data-confirm"=>"本当に削除しますか？",class:"btn btn-danger" %></td>
      <% else %>
        <% if book.favorited_by? (current_user) %>
          <td>
            <%= link_to book_favorites_path(book.id),method: :delete do %>
              <p class="text-danger">♡<%= book.favorites.count %>いいね</p>
            <% end %>
          </td>
        <% else %>
        <td>
          <%= link_to book_favorites_path(book.id),method: :post do %>
            <p class="text-primary">♡<%= book.favorites.count %>いいね</p>
          <% end %>
        </td>
        <% end %>
       <td>コメント件数:<%= book.comments.count %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.html.erb
<div class="mt-5">
<%if book.errors.any? %>
  <div class="text-danger border border-danger fs-6">
    <p><%= book.errors.count %>件のエラーがありました</p>
    <% book.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>
<%= flash[:create] %>

<h3>新規投稿</h3>
<%= form_with model:book,local:true do |f| %>
  <p>タイトル</p>
  <%= f.text_field:title ,class:"form-control" %>
  <p class="mt-3">概要</p>
  <%= f.text_area:body,class:"form-control" %>
  <%= f.submit "登録" ,class:"btn btn-primary btn-block mt-3" %>
<% end %>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "users/profile",user:@user,favorites_count:@favorites_count %>
      <%= render "books/new",book:@book %>
    </div>
    <div class="col-lg-9">
      <%= render "books/list",books:@books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <p>新規投稿</p>
        <%= form_with(model:[@select_book,@comment],local:true) do |f| %>
        <%= f.text_area:comment,placeholder:"コメントをここに",class:"form-control input-lg d-inline-block" %>
        <%= f.submit "投稿する" ,class:"btn btn-secondary"%>
        <% end %>
    </div>
    <div class="col-lg-9">
     <h1><%= @select_book.title %>-コメント件数:<%= @select_book.comments.count %></h1>
     <table class="table">
       <thead>
         <td>user_info</td>
         <td>comment</td>
         <td>time</td>
       </thead>
       <% @select_book.comments.each do |comment| %>
       <tr>
         <td>
           <%= attachment_image_tag comment.user ,:profile_image,fallback:"no_image.jpg",size:"60x66" %><br>
           <%= comment.user.name %>
         </td>
         <td><%= comment.comment %></td>
         <td><%= comment.created_at.strftime("%Y/%m/%d") %></td>
       </tr>
       <% end %>
      </table>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<h1>コメント一覧</h1>
<

app/views/homes/top.html.erb
<h1>トップページ</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm mb-3">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <h1 class="navbar-brand p-3">bookers</h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target"#navbarNavDropdown" aria-control="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdow">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <%= link_to user_path(current_user.id) do %><li class="nav-item nav-link mx-2">Home</li><% end %>
            <%= link_to books_path do %><li class="nav-item nav-link mx-2">Books</li><% end %>
            <%= link_to destroy_user_session_path,method: :delete do %><li class="nav-item nav-link mx2">Log out</li><% end %>
            <% else %>
            <li class="nav-item mx2"><span class="nav-link">About</span></li>
            <%= link_to new_user_registration_path do %><li class="nav-item mx-2 nav-link">Sign up</li><% end %>
            <%= link_to new_user_session_path do %><li class="nav-item mx-2 nav-link">Sign in</li><% end %>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <%= form_tag(search_path,method: :get) do %>
              <%= text_field_tag "content" %>
              <%= select_tag "model" ,options_for_select({"ユーザー"=>"user","投稿"=>"book"}) %>
              <%= select_tag "method" ,options_for_select({"完全一致"=>"perfect","部分一致"=>"partial"}) %>
              <%= submit_tag "検索" %>
            <% end %>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/searchs/search.html.erb
<h1>検索結果/検索ワード:<%= @content%></h1>
<% if @model=="user" %>
  <table class="table">
    <thead>
      <th>image</th>
      <th>name</th>
    </thead>
    <% @records.each do |user| %>
    <tr>
      <td><%= attachment_image_tag user,:profile_image,fallback:"no_image.jpg",size:"60x66" %></td>
      <td><%= user.name %></td>
    </tr>
    <% end %>
  </table>
<% elsif @model=="book" %>
  <table class="table">
    <thead>
      <th>image</t>
      <th>title</th>
      <th>body</th>
    </thead>
    <% @records.each do |book| %>
    <tr>
      <td><%= attachment_image_tag book.user,:profile_image,fallback:"no_image.jpg",size:"60x66" %></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </table>
<% else %>
  <h3>検索結果なし</h3>
<% end %>

app/views/users/_profile.html.erb
<div class="card w-100 mx-auto shadow-sm">
  <%= attachment_image_tag user,:profile_image,fallback:"no_image.jpg",class:"card-img-top" %>
  <div class="card-body">
    <div class="row mx-auto">
    <h4><%= user.name %></h4>
    <%= link_to edit_user_path(user.id) do %><p class="btn btn-outline-secondary btn-sm ml-3">編集</p><% end %>
    </div>
    <p>いいねの数:<%= favorites_count %></p>
  </div>
</div>

app/views/users/edit.html.erb
<h3>編集画面</h3>

<%= form_with model:@user,local:true do |f| %>

<p><%= f.text_field:name %></p>

<p><%= f.attachment_field:profile_image %></p>

<p><%= f.submit "更新" %></p>


<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <%= render "users/profile",user:@user,favorites_count:@favorites_count  %>
      <%= render "books/new",book:@book %>
    </div>
    <div class="col-lg-9">
      <%= render "books/list",books:@books %>
    </div>
  </div>
</div>